---
version: '3'
services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: "jobfair-skripsi"
      POSTGRES_DB: "jobfair-skripsi"
      POSTGRES_PASSWORD: "jobfair-skripsi"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data/pgdata
      - ./:/docker-entrypoint-initdb.d/
